<a href="https://colab.research.google.com/github/yohana143/INT248/blob/main/Hand_Written_digits_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing the necessary libraries 

In [32]:
import tensorflow as tf
import keras
from keras import utils as np_utils
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D,MaxPooling2D
from keras import backend as k
import pandas as pd

#Data Splitting

In [24]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [25]:
print(x_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [26]:
print(x_test.shape)
print(y_test.shape)

(10000, 28, 28)
(10000,)


In [27]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

#Data Preprocessing

In [28]:
x_train=x_train.reshape(len(x_train),28*28)
x_test=x_test.reshape(len(x_test),28*28)

In [29]:
x_train.shape

(60000, 784)

#Since CNN accepts only binary values,we convert each class vector to binary class matrices

In [9]:
y_train=keras.utils.to_categorical(y_train,10)
x_test=keras.utils.to_categorical(y_test,10)

In [10]:
print("The y_train data is:\n\n",y_train)
print("\n")
print("The x_test data is:\n\n",x_test)

The y_train data is:

 [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


The x_test data is:

 [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
x_train =x_train.astype("float32")
x_test=x_test.astype("float32")

In [12]:
x_train=x_train/255
x_test=x_test/255

In [13]:
x_train.shape

(60000, 28, 28, 1)

In [14]:
#Total training samples
x_train.shape[0]

60000

In [15]:
#Total testing samples
x_test.shape[0]

10000

#Building the model

In [35]:
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

model.compile(
    loss=keras.losses.categorical_crossentropy,optimizer='adam',metrics=['accuracy']
)

#Training the model

In [36]:
model.fit(x_train,y_train,batch_size=128,epochs=10,verbose=1,validation_data=(x_test,y_test))

#model.save(mnist)

Epoch 1/10


ValueError: ignored